name: infrastructure
services:
  pgadmin:
    container_name: veridata.pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_LISTEN_PORT}:80"
    networks:
      veridata.network:
        aliases:
          - veridata.pgadmin

networks:
  veridata.network:
    external: true
