name: veridata

services:
  veridata_rag:
    build: .
    restart: unless-stopped
    container_name: veridata.rag
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      veridata.network:
        aliases:
          - veridata.rag


networks:
  veridata.network:
    external: true
