name: databases
services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: veridata.postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    shm_size: "1gb"
    ports:
      # Access from outside via SSH Tunnel only.
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      veridata.network:
        aliases:
          - veridata.postgres

volumes:
  postgres_data:

networks:
  veridata.network:
    external: true
