[project]
name = "vdbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "aiocache>=0.12.3",
    "bcrypt>=4.1.2",
    "fastapi>=0.118.0",
    "httpx>=0.28.1",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.37.0",
    "asyncpg>=0.30.0",
    "jinja2>=3.1.2",
]

[tool.uv]
package = true
