services:
  api:
    build: .
    container_name: veridata.rag
    env_file:
      - .env
    environment:
      # Connect to external postgres container
      DATABASE_URL: postgresql://${POSTGRES_USER:-vd}:${POSTGRES_PASSWORD:-vd}@veridata.postgres:5432/${POSTGRES_DB:-veridata_rag}
    ports:
      - "${API_PORT:-8000}:8000"
    networks:
      veridata.network:
        aliases:
          - veridata.rag
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./pyproject.toml

networks:
  veridata.network:
    external: true
