services:
  espocrm:
    image: espocrm/espocrm:9.2.7-apache
    container_name: ${CONTAINER_NAME-espocrm}
    restart: always
    environment:
      - ESPOCRM_DATABASE_PLATFORM=Postgresql
      - ESPOCRM_DATABASE_HOST=${POSTGRES_HOST}
      - ESPOCRM_DATABASE_PORT=${POSTGRES_PORT}
      - ESPOCRM_DATABASE_USER=${POSTGRES_USER}
      - ESPOCRM_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - ESPOCRM_DATABASE_NAME=${POSTGRES_DB}
      - ESPOCRM_ADMIN_USERNAME=${ESPOCRM_ADMIN_USERNAME}
      - ESPOCRM_ADMIN_PASSWORD=${ESPOCRM_ADMIN_PASSWORD}
      - ESPOCRM_SITE_URL=${ESPOCRM_SITE_URL-http://localhost:4012}
    ports:
      - "${ESPOCRM_PORT}:80"
    volumes: &espocrm_volumes
      - espocrm_data:/var/www/html/data
      - espocrm_custom:/var/www/html/custom
      - espocrm_client_custom:/var/www/html/client/custom
      - espocrm_logs:/var/www/html/data/logs
    networks:
      veridata.network:
        aliases:
          - veridata.${CONTAINER_NAME-espocrm}.rails

  espocrm-daemon:
    image: espocrm/espocrm:latest
    container_name: ${CONTAINER_NAME-espocrm}-daemon
    command: bash -c "while true; do php /var/www/html/cron.php; sleep 60; done"
    restart: always
    volumes: *espocrm_volumes
    networks:
      veridata.network:
        aliases:
          - veridata.${CONTAINER_NAME-espocrm}.daemon

  espocrm-websocket:
    image: espocrm/espocrm:latest
    container_name: ${CONTAINER_NAME-espocrm}-websocket
    command: php /var/www/html/bin/websocket.php
    restart: always
    environment:
      - ESPOCRM_CONFIG_USE_WEB_SOCKET=true
    volumes: *espocrm_volumes
    networks:
      veridata.network:
        aliases:
          - veridata.${CONTAINER_NAME-espocrm}.websocket

volumes:
  espocrm_data:
    name: ${VOLUME_NAME-espocrm}_data
  espocrm_custom:
    name: ${VOLUME_NAME-espocrm}_custom
  espocrm_client_custom:
    name: ${VOLUME_NAME-espocrm}_client_custom
  espocrm_logs:
    name: ${VOLUME_NAME-espocrm}_logs

networks:
  veridata.network:
    external: true