name: veriops

services:
  veridata_bot:
    build:
      context: .
    container_name: veridata.bot
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    env_file:
      - .env
    ports:
      - "${VDBOT_PORT:-8080}:8080"
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    networks:
      veridata.network:
        aliases:
          - veridata.bot

networks:
  veridata.network:
    external: true